/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 XL_Three.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function XLThree() {
  const { nodes, materials } = useGLTF('/XL_Three.glb')
  return ( 
    <group  dispose={null}>
      <group scale={0.01}>
        <group position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <group position={[-0.005, -0.002, 0]}>
            <group position={[0.005, -1.747, 0.921]}>
              <mesh geometry={nodes.boot_boot6_0.geometry} material={materials['boot.6']} />
              <mesh geometry={nodes.boot_movsteer_100_0.geometry} material={materials['movsteer_1.0.0']} />
              <mesh geometry={nodes.boot_movsteer_103_0.geometry} material={materials['movsteer_1.0.3']} />
              <mesh geometry={nodes.boot_movsteer_107_0.geometry} material={materials['movsteer_1.0.7']} />
              <mesh geometry={nodes.boot_primary_0.geometry} material={materials.primary} />
              <mesh geometry={nodes.boot_wheel_rf0_0.geometry} material={materials['wheel_rf.0']} />
              <mesh geometry={nodes.boot_wheel_rf1_0.geometry} material={materials['wheel_rf.1']} />
              <mesh geometry={nodes.boot_wheel_rf5_0.geometry} material={materials['wheel_rf.5']} />
              <mesh geometry={nodes.boot_xl6_ext_b_021_0.geometry} material={materials['xl6_ext_b_02.1']} />
              <mesh geometry={nodes.boot_led_right_front_light_0.geometry} material={materials.right_front_light} />
              <mesh geometry={nodes.boot_taillight_glass_glass001_0.geometry} material={materials['glass.001']} />
              <mesh geometry={nodes.boot001_boot0_0.geometry} material={materials['boot.0']} position={[0, 3.653, -1.34]} />
              <mesh geometry={nodes.boot_windscreen_glass_0.geometry} material={materials.glass} />
              <mesh geometry={nodes.breaklight_l002_left_rear_light_0.geometry} material={materials.left_rear_light} />
              <mesh geometry={nodes.breaklight_r002_right_rear_light_0.geometry} material={materials.right_rear_light} />
            </group>
            <group position={[0.005, 1.906, -0.419]}>
              <mesh geometry={nodes.chassis_primary_0.geometry} material={materials.primary} />
              <mesh geometry={nodes.chassis_wheel_rf0_0.geometry} material={materials['wheel_rf.0']} />
              <mesh geometry={nodes.carpet_carpet0_0.geometry} material={materials['carpet.0']} />
              <mesh geometry={nodes.carpet_carpet10_0.geometry} material={materials['carpet.10']} />
              <mesh geometry={nodes.carpet_carpet11_0.geometry} material={materials['carpet.11']} />
              <mesh geometry={nodes.carpet_movsteer_100_0.geometry} material={materials['movsteer_1.0.0']} />
              <mesh geometry={nodes.carpet_movsteer_101_0.geometry} material={materials['movsteer_1.0.1']} />
              <mesh geometry={nodes.carpet_movsteer_103_0.geometry} material={materials['movsteer_1.0.3']} />
              <mesh geometry={nodes.carpet_movsteer_107_0.geometry} material={materials['movsteer_1.0.7']} />
              <mesh geometry={nodes.carpet_movsteer_109_0.geometry} material={materials['movsteer_1.0.9']} />
              <mesh geometry={nodes.carpet_wheel_rf0_0.geometry} material={materials['wheel_rf.0']} />
              <mesh geometry={nodes.carpet_wheel_rf1_0.geometry} material={materials['wheel_rf.1']} />
              <mesh geometry={nodes.carpet_wheel_rf5_0.geometry} material={materials['wheel_rf.5']} />
              <mesh geometry={nodes.carpet_xl6_int_b_seats1_0.geometry} material={materials['xl6_int_b_seats.1']} />
              <mesh geometry={nodes.plate_front_movsteer_107_0.geometry} material={materials['movsteer_1.0.7']} />
              <mesh geometry={nodes.plate_front_xl6_ext_b_021_0.geometry} material={materials['xl6_ext_b_02.1']} />
              <mesh geometry={nodes.xl6_ext_b_02_primary_0.geometry} material={materials.primary} />
              <mesh geometry={nodes.xl6_ext_b_02_xl6_ext_b_021_0.geometry} material={materials['xl6_ext_b_02.1']} />
              <mesh geometry={nodes.xl6_ext_b_03_movsteer_103_0.geometry} material={materials['movsteer_1.0.3']} />
              <mesh geometry={nodes.xl6_ext_b_03_wheel_rf0_0.geometry} material={materials['wheel_rf.0']} />
              <mesh geometry={nodes.xl6_ext_b_03_wheel_rf4_0.geometry} material={materials['wheel_rf.4']} />
              <mesh geometry={nodes.xl6_ext_b_03_xl6_ext_b_021_0.geometry} material={materials['xl6_ext_b_02.1']} />
              <mesh geometry={nodes.xl6_ext_b_04_xl6_ext_b_021_0.geometry} material={materials['xl6_ext_b_02.1']} />
              <mesh geometry={nodes.xl6_ext_b_05_xl6_ext_b_021_0.geometry} material={materials['xl6_ext_b_02.1']} />
              <mesh geometry={nodes.xl6_ext_b_06_wheel_rf0_0.geometry} material={materials['wheel_rf.0']} />
              <mesh geometry={nodes.xl6_ext_b_06_xl6_ext_b_021_0.geometry} material={materials['xl6_ext_b_02.1']} />
              <mesh geometry={nodes.xl6_ext_b_07_wheel_rf0_0.geometry} material={materials['wheel_rf.0']} />
              <mesh geometry={nodes.xl6_ext_b_07_xl6_ext_b_021_0.geometry} material={materials['xl6_ext_b_02.1']} />
              <mesh geometry={nodes.xl6_ext_b_bumper_r_primary_0.geometry} material={materials.primary} />
              <mesh geometry={nodes.xl6_ext_b_bumper_r_xl6_ext_b_021_0.geometry} material={materials['xl6_ext_b_02.1']} />
              <mesh geometry={nodes.xl6_ext_b_carpaint_primary_0.geometry} material={materials.primary} />
              <mesh geometry={nodes.xl6_ext_b_grille_d_wheel_rf5_0.geometry} material={materials['wheel_rf.5']} />
              <mesh geometry={nodes.xl6_ext_b_grille_f_wheel_rf0_0.geometry} material={materials['wheel_rf.0']} />
              <mesh geometry={nodes.xl6_ext_b_grille_f_wheel_rf1_0.geometry} material={materials['wheel_rf.1']} />
              <mesh geometry={nodes.xl6_ext_b_grille_f_wheel_rf5_0.geometry} material={materials['wheel_rf.5']} />
              <mesh geometry={nodes.xl6_ext_b_grille_f_xl6_ext_b_021_0.geometry} material={materials['xl6_ext_b_02.1']} />
              <mesh geometry={nodes.xl6_ext_b_headlight_led_wheel_rf5_0.geometry} material={materials['wheel_rf.5']} />
              <mesh geometry={nodes.foglight_l_foglight_l_0.geometry} material={materials.foglight_l} />
              <mesh geometry={nodes.foglight_r_foglight_r_0.geometry} material={materials.foglight_r} />
              <mesh geometry={nodes.headlight_led_right_front_light_0.geometry} material={materials.right_front_light} />
              <mesh geometry={nodes.headlight_led2_right_front_light_0.geometry} material={materials.right_front_light} />
              <mesh geometry={nodes.indicator_lf001_indicator_lf_0.geometry} material={materials.indicator_lf} />
              <mesh geometry={nodes.indicator_rf001_indicator_rf_0.geometry} material={materials.indicator_rf} />
              <mesh geometry={nodes.xl6_ext_b_headlight_glass_glass001_0.geometry} material={materials['glass.001']} />
              <mesh geometry={nodes.xl6_ext_b_headlight_glass_glass_0.geometry} material={materials.glass} />
              <mesh geometry={nodes.xl6_ext_b_roofrail_wheel_rf5_0.geometry} material={materials['wheel_rf.5']} />
              <mesh geometry={nodes.xl6_ext_b_taillights_led_movsteer_103_0.geometry} material={materials['movsteer_1.0.3']} />
              <mesh geometry={nodes.xl6_ext_b_taillights_led_wheel_rf0_0.geometry} material={materials['wheel_rf.0']} />
              <mesh geometry={nodes.xl6_ext_b_taillights_led_xl6_ext_b_021_0.geometry} material={materials['xl6_ext_b_02.1']} />
              <mesh geometry={nodes.breaklight_l001_left_rear_light_0.geometry} material={materials.left_rear_light} />
              <mesh geometry={nodes.breaklight_r001_right_rear_light_0.geometry} material={materials.right_rear_light} />
              <mesh geometry={nodes.indicator_lr001_indicator_lr_0.geometry} material={materials.indicator_lr} />
              <mesh geometry={nodes.indicator_rr001_indicator_rr_0.geometry} material={materials.indicator_rr} />
              <mesh geometry={nodes.reversinglight_l001_revlight_L_0.geometry} material={materials.revlight_L} />
              <mesh geometry={nodes.reversinglight_r001_revlight_r_0.geometry} material={materials.revlight_r} />
              <mesh geometry={nodes.taillight_r_glass_glass001_0.geometry} material={materials['glass.001']} />
              <mesh geometry={nodes.taillight_r_glass_glass002_0.geometry} material={materials['glass.002']} />
              <mesh geometry={nodes.xl6_ext_b_windows_glass_0.geometry} material={materials.glass} />
              <mesh geometry={nodes.xl6_int_b_02_movsteer_103_0.geometry} material={materials['movsteer_1.0.3']} />
              <mesh geometry={nodes.xl6_int_b_03_wheel_rf0_0.geometry} material={materials['wheel_rf.0']} />
              <mesh geometry={nodes.xl6_int_b_04_movsteer_100_0.geometry} material={materials['movsteer_1.0.0']} />
              <mesh geometry={nodes.xl6_int_b_04_movsteer_101_0.geometry} material={materials['movsteer_1.0.1']} />
              <mesh geometry={nodes.xl6_int_b_04_movsteer_103_0.geometry} material={materials['movsteer_1.0.3']} />
              <mesh geometry={nodes.xl6_int_b_04_movsteer_107_0.geometry} material={materials['movsteer_1.0.7']} />
              <mesh geometry={nodes.xl6_int_b_05_movsteer_101_0.geometry} material={materials['movsteer_1.0.1']} />
              <mesh geometry={nodes.xl6_int_b_05_movsteer_103_0.geometry} material={materials['movsteer_1.0.3']} />
              <mesh geometry={nodes.xl6_int_b_05_movsteer_107_0.geometry} material={materials['movsteer_1.0.7']} />
              <mesh geometry={nodes.xl6_int_b_05_wheel_rf0_0.geometry} material={materials['wheel_rf.0']} />
              <mesh geometry={nodes.xl6_int_b_05_wheel_rf4_0.geometry} material={materials['wheel_rf.4']} />
              <mesh geometry={nodes.xl6_int_b_05_wheel_rf5_0.geometry} material={materials['wheel_rf.5']} />
              <mesh geometry={nodes.xl6_int_b_05_xl6_int_b_seats1_0.geometry} material={materials['xl6_int_b_seats.1']} />
              <mesh geometry={nodes.xl6_int_b_06_movsteer_101_0.geometry} material={materials['movsteer_1.0.1']} />
              <mesh geometry={nodes.xl6_int_b_06_movsteer_103_0.geometry} material={materials['movsteer_1.0.3']} />
              <mesh geometry={nodes.xl6_int_b_06_wheel_rf0_0.geometry} material={materials['wheel_rf.0']} />
              <mesh geometry={nodes.xl6_int_b_06_wheel_rf1_0.geometry} material={materials['wheel_rf.1']} />
              <mesh geometry={nodes.xl6_int_b_06_wheel_rf4_0.geometry} material={materials['wheel_rf.4']} />
              <mesh geometry={nodes.xl6_int_b_06_wheel_rf5_0.geometry} material={materials['wheel_rf.5']} />
              <mesh geometry={nodes.xl6_int_b_06_xl6_int_b_067_0.geometry} material={materials['xl6_int_b_06.7']} />
              <mesh geometry={nodes.xl6_int_b_06_xl6_int_b_068_0.geometry} material={materials['xl6_int_b_06.8']} />
              <mesh geometry={nodes.xl6_int_b_06_xl6_int_b_069_0.geometry} material={materials['xl6_int_b_06.9']} />
              <mesh geometry={nodes.xl6_int_b_06_xl6_int_b_seats1_0.geometry} material={materials['xl6_int_b_seats.1']} />
              <mesh geometry={nodes.xl6_int_b_console_movsteer_100_0.geometry} material={materials['movsteer_1.0.0']} />
              <mesh geometry={nodes.xl6_int_b_console_movsteer_101_0.geometry} material={materials['movsteer_1.0.1']} />
              <mesh geometry={nodes.xl6_int_b_console_movsteer_103_0.geometry} material={materials['movsteer_1.0.3']} />
              <mesh geometry={nodes.xl6_int_b_console_movsteer_109_0.geometry} material={materials['movsteer_1.0.9']} />
              <mesh geometry={nodes.xl6_int_b_console_wheel_rf0_0.geometry} material={materials['wheel_rf.0']} />
              <mesh geometry={nodes.xl6_int_b_console_wheel_rf5_0.geometry} material={materials['wheel_rf.5']} />
              <mesh geometry={nodes.xl6_int_b_console_xl6_int_b_dashboard4_0.geometry} material={materials['xl6_int_b_dashboard.4']} />
              <mesh geometry={nodes.xl6_int_b_console_xl6_int_b_seats1_0.geometry} material={materials['xl6_int_b_seats.1']} />
              <mesh geometry={nodes.xl6_int_b_dashboard_movsteer_100_0.geometry} material={materials['movsteer_1.0.0']} />
              <mesh geometry={nodes.xl6_int_b_dashboard_movsteer_101_0.geometry} material={materials['movsteer_1.0.1']} />
              <mesh geometry={nodes.xl6_int_b_dashboard_movsteer_103_0.geometry} material={materials['movsteer_1.0.3']} />
              <mesh geometry={nodes.xl6_int_b_dashboard_movsteer_107_0.geometry} material={materials['movsteer_1.0.7']} />
              <mesh geometry={nodes.xl6_int_b_dashboard_movsteer_109_0.geometry} material={materials['movsteer_1.0.9']} />
              <mesh geometry={nodes.xl6_int_b_dashboard_wheel_rf0_0.geometry} material={materials['wheel_rf.0']} />
              <mesh geometry={nodes.xl6_int_b_dashboard_wheel_rf1_0.geometry} material={materials['wheel_rf.1']} />
              <mesh geometry={nodes.xl6_int_b_dashboard_wheel_rf5_0.geometry} material={materials['wheel_rf.5']} />
              <mesh geometry={nodes.xl6_int_b_dashboard_xl6_int_b_dashboard4_0.geometry} material={materials['xl6_int_b_dashboard.4']} />
              <mesh geometry={nodes.xl6_int_b_dashboard_xl6_int_b_seats1_0.geometry} material={materials['xl6_int_b_seats.1']} />
              <mesh geometry={nodes.dashboard_screenglass_glass_0.geometry} material={materials.glass} />
              <mesh geometry={nodes.dashboard_speed_glass_glass_0.geometry} material={materials.glass} />
              <mesh geometry={nodes.xl6_int_b_seats_movsteer_100_0.geometry} material={materials['movsteer_1.0.0']} />
              <mesh geometry={nodes.xl6_int_b_seats_movsteer_103_0.geometry} material={materials['movsteer_1.0.3']} />
              <mesh geometry={nodes.xl6_int_b_seats_xl6_ext_b_021_0.geometry} material={materials['xl6_ext_b_02.1']} />
              <mesh geometry={nodes.xl6_int_b_seats_xl6_int_b_seats1_0.geometry} material={materials['xl6_int_b_seats.1']} />
              <mesh geometry={nodes.xl6_int_b_seats_xl6_int_b_seats4_0.geometry} material={materials['xl6_int_b_seats.4']} />
              <mesh geometry={nodes.xl6_int_b_sidewall_movsteer_100_0.geometry} material={materials['movsteer_1.0.0']} />
              <mesh geometry={nodes.xl6_int_b_sidewall_movsteer_103_0.geometry} material={materials['movsteer_1.0.3']} />
              <mesh geometry={nodes.xl6_int_b_sidewall_wheel_rf0_0.geometry} material={materials['wheel_rf.0']} />
              <mesh geometry={nodes.xl6_int_b_sidewall_wheel_rf1_0.geometry} material={materials['wheel_rf.1']} />
              <mesh geometry={nodes.xl6_int_b_sidewall_wheel_rf4_0.geometry} material={materials['wheel_rf.4']} />
              <mesh geometry={nodes.xl6_int_b_sidewall_wheel_rf5_0.geometry} material={materials['wheel_rf.5']} />
              <mesh geometry={nodes.xl6_int_b_sidewall_xl6_int_b_067_0.geometry} material={materials['xl6_int_b_06.7']} />
              <mesh geometry={nodes.xl6_int_b_sidewall_xl6_int_b_068_0.geometry} material={materials['xl6_int_b_06.8']} />
              <mesh geometry={nodes.xl6_int_b_sidewall_xl6_int_b_seats1_0.geometry} material={materials['xl6_int_b_seats.1']} />
              <mesh geometry={nodes.xl6_int_b_spedometer_movsteer_100_0.geometry} material={materials['movsteer_1.0.0']} />
              <mesh geometry={nodes.xl6_int_b_spedometer_movsteer_101_0.geometry} material={materials['movsteer_1.0.1']} />
              <mesh geometry={nodes.xl6_int_b_spedometer_movsteer_103_0.geometry} material={materials['movsteer_1.0.3']} />
              <mesh geometry={nodes.xl6_int_b_spedometer_movsteer_108_0.geometry} material={materials['movsteer_1.0.8']} />
              <mesh geometry={nodes.xl6_int_b_spedometer_wheel_rf0_0.geometry} material={materials['wheel_rf.0']} />
              <mesh geometry={nodes.xl6_int_b_spedometer_wheel_rf5_0.geometry} material={materials['wheel_rf.5']} />
              <mesh geometry={nodes.speedoeter_symbols_movsteer_107_0.geometry} material={materials['movsteer_1.0.7']} />
            </group>
            <group position={[-0.847, 0.968, 0.092]}>
              <mesh geometry={nodes.door_lf_movsteer_100_0.geometry} material={materials['movsteer_1.0.0']} />
              <mesh geometry={nodes.door_lf_movsteer_101_0.geometry} material={materials['movsteer_1.0.1']} />
              <mesh geometry={nodes.door_lf_movsteer_103_0.geometry} material={materials['movsteer_1.0.3']} />
              <mesh geometry={nodes.door_lf_movsteer_107_0.geometry} material={materials['movsteer_1.0.7']} />
              <mesh geometry={nodes.door_lf_movsteer_109_0.geometry} material={materials['movsteer_1.0.9']} />
              <mesh geometry={nodes.door_lf_primary_0.geometry} material={materials.primary} />
              <mesh geometry={nodes.door_lf_wheel_rf0_0.geometry} material={materials['wheel_rf.0']} />
              <mesh geometry={nodes.door_lf_wheel_rf5_0.geometry} material={materials['wheel_rf.5']} />
              <mesh geometry={nodes.door_lf_xl6_int_b_seats1_0.geometry} material={materials['xl6_int_b_seats.1']} />
              <mesh geometry={nodes.door_lf_glass_glass_0.geometry} material={materials.glass} />
              <mesh geometry={nodes.indicator_lm_indicator_lm_0.geometry} material={materials.indicator_lm} />
            </group>
            <group position={[-0.851, -0.043, 0.097]}>
              <mesh geometry={nodes.door_lr_movsteer_100_0.geometry} material={materials['movsteer_1.0.0']} />
              <mesh geometry={nodes.door_lr_movsteer_101_0.geometry} material={materials['movsteer_1.0.1']} />
              <mesh geometry={nodes.door_lr_movsteer_103_0.geometry} material={materials['movsteer_1.0.3']} />
              <mesh geometry={nodes.door_lr_movsteer_107_0.geometry} material={materials['movsteer_1.0.7']} />
              <mesh geometry={nodes.door_lr_movsteer_109_0.geometry} material={materials['movsteer_1.0.9']} />
              <mesh geometry={nodes.door_lr_primary_0.geometry} material={materials.primary} />
              <mesh geometry={nodes.door_lr_wheel_rf0_0.geometry} material={materials['wheel_rf.0']} />
              <mesh geometry={nodes.door_lr_wheel_rf5_0.geometry} material={materials['wheel_rf.5']} />
              <mesh geometry={nodes.door_lr_xl6_int_b_seats1_0.geometry} material={materials['xl6_int_b_seats.1']} />
              <mesh geometry={nodes.door_lr_glass_glass_0.geometry} material={materials.glass} />
            </group>
            <group position={[0.858, 0.969, 0.092]}>
              <mesh geometry={nodes.door_rf_movsteer_100_0.geometry} material={materials['movsteer_1.0.0']} />
              <mesh geometry={nodes.door_rf_movsteer_101_0.geometry} material={materials['movsteer_1.0.1']} />
              <mesh geometry={nodes.door_rf_movsteer_103_0.geometry} material={materials['movsteer_1.0.3']} />
              <mesh geometry={nodes.door_rf_movsteer_107_0.geometry} material={materials['movsteer_1.0.7']} />
              <mesh geometry={nodes.door_rf_movsteer_109_0.geometry} material={materials['movsteer_1.0.9']} />
              <mesh geometry={nodes.door_rf_primary_0.geometry} material={materials.primary} />
              <mesh geometry={nodes.door_rf_wheel_rf0_0.geometry} material={materials['wheel_rf.0']} />
              <mesh geometry={nodes.door_rf_wheel_rf5_0.geometry} material={materials['wheel_rf.5']} />
              <mesh geometry={nodes.door_rf_xl6_int_b_dashboard4_0.geometry} material={materials['xl6_int_b_dashboard.4']} />
              <mesh geometry={nodes.door_rf_xl6_int_b_seats1_0.geometry} material={materials['xl6_int_b_seats.1']} />
              <mesh geometry={nodes.door_rf_glass_glass_0.geometry} material={materials.glass} />
              <mesh geometry={nodes.indicator_rm_indicator_rm_0.geometry} material={materials.indicator_rm} />
            </group>
            <group position={[0.862, -0.042, 0.097]}>
              <mesh geometry={nodes.door_rr_movsteer_100_0.geometry} material={materials['movsteer_1.0.0']} />
              <mesh geometry={nodes.door_rr_movsteer_101_0.geometry} material={materials['movsteer_1.0.1']} />
              <mesh geometry={nodes.door_rr_movsteer_103_0.geometry} material={materials['movsteer_1.0.3']} />
              <mesh geometry={nodes.door_rr_movsteer_107_0.geometry} material={materials['movsteer_1.0.7']} />
              <mesh geometry={nodes.door_rr_movsteer_109_0.geometry} material={materials['movsteer_1.0.9']} />
              <mesh geometry={nodes.door_rr_primary_0.geometry} material={materials.primary} />
              <mesh geometry={nodes.door_rr_wheel_rf0_0.geometry} material={materials['wheel_rf.0']} />
              <mesh geometry={nodes.door_rr_wheel_rf5_0.geometry} material={materials['wheel_rf.5']} />
              <mesh geometry={nodes.door_rr_xl6_int_b_seats1_0.geometry} material={materials['xl6_int_b_seats.1']} />
              <mesh geometry={nodes.door_rr_glass_glass_0.geometry} material={materials.glass} />
            </group>
            <group position={[0.335, 0.54, 0.294]} rotation={[-0.525, 0, 0]}>
              <group position={[0, 0.052, 0.022]} rotation={[0.017, 0, 0]}>
                <mesh geometry={nodes.movsteer_10_movsteer_100_0.geometry} material={materials['movsteer_1.0.0']} />
                <mesh geometry={nodes.movsteer_10_movsteer_101_0.geometry} material={materials['movsteer_1.0.1']} />
                <mesh geometry={nodes.movsteer_10_movsteer_103_0.geometry} material={materials['movsteer_1.0.3']} />
                <mesh geometry={nodes.movsteer_10_movsteer_105_0.geometry} material={materials['movsteer_1.0.5']} />
                <mesh geometry={nodes.movsteer_10_movsteer_107_0.geometry} material={materials['movsteer_1.0.7']} />
                <mesh geometry={nodes.movsteer_10_movsteer_108_0.geometry} material={materials['movsteer_1.0.8']} />
                <mesh geometry={nodes.movsteer_10_movsteer_109_0.geometry} material={materials['movsteer_1.0.9']} />
                <mesh geometry={nodes.movsteer_10_wheel_rf0_0.geometry} material={materials['wheel_rf.0']} />
                <mesh geometry={nodes.movsteer_10_wheel_rf1_0.geometry} material={materials['wheel_rf.1']} />
                <mesh geometry={nodes.movsteer_10_wheel_rf5_0.geometry} material={materials['wheel_rf.5']} />
              </group>
            </group>
          </group>
          <group position={[0.759, 1.362, -0.394]}>
            <group position={[0, -2.736, 0]}>
              <mesh geometry={nodes.wheel_rf001_wheel_rf0_0.geometry} material={materials['wheel_rf.0']} />
              <mesh geometry={nodes.wheel_rf001_wheel_rf1_0.geometry} material={materials['wheel_rf.1']} />
              <mesh geometry={nodes.wheel_rf001_wheel_rf2_0.geometry} material={materials['wheel_rf.2']} />
              <mesh geometry={nodes.wheel_rf001_wheel_rf3_0.geometry} material={materials['wheel_rf.3']} />
              <mesh geometry={nodes.wheel_rf001_wheel_rf4_0.geometry} material={materials['wheel_rf.4']} />
              <mesh geometry={nodes.wheel_rf001_wheel_rf5_0.geometry} material={materials['wheel_rf.5']} />
            </group>
            <group position={[-1.519, 0, 0]} rotation={[-Math.PI, 0, 0]} scale={-1}>
              <mesh geometry={nodes.wheel_rf002_wheel_rf0_0.geometry} material={materials['wheel_rf.0']} />
              <mesh geometry={nodes.wheel_rf002_wheel_rf1_0.geometry} material={materials['wheel_rf.1']} />
              <mesh geometry={nodes.wheel_rf002_wheel_rf2_0.geometry} material={materials['wheel_rf.2']} />
              <mesh geometry={nodes.wheel_rf002_wheel_rf3_0.geometry} material={materials['wheel_rf.3']} />
              <mesh geometry={nodes.wheel_rf002_wheel_rf4_0.geometry} material={materials['wheel_rf.4']} />
              <mesh geometry={nodes.wheel_rf002_wheel_rf5_0.geometry} material={materials['wheel_rf.5']} />
            </group>
            <group position={[-1.519, -2.738, 0]} rotation={[-Math.PI, 0, 0]} scale={-1}>
              <mesh geometry={nodes.wheel_rf003_wheel_rf0_0.geometry} material={materials['wheel_rf.0']} />
              <mesh geometry={nodes.wheel_rf003_wheel_rf1_0.geometry} material={materials['wheel_rf.1']} />
              <mesh geometry={nodes.wheel_rf003_wheel_rf2_0.geometry} material={materials['wheel_rf.2']} />
              <mesh geometry={nodes.wheel_rf003_wheel_rf3_0.geometry} material={materials['wheel_rf.3']} />
              <mesh geometry={nodes.wheel_rf003_wheel_rf4_0.geometry} material={materials['wheel_rf.4']} />
              <mesh geometry={nodes.wheel_rf003_wheel_rf5_0.geometry} material={materials['wheel_rf.5']} />
            </group>
            <mesh geometry={nodes.wheel_rf_wheel_rf0_0.geometry} material={materials['wheel_rf.0']} />
            <mesh geometry={nodes.wheel_rf_wheel_rf1_0.geometry} material={materials['wheel_rf.1']} />
            <mesh geometry={nodes.wheel_rf_wheel_rf2_0.geometry} material={materials['wheel_rf.2']} />
            <mesh geometry={nodes.wheel_rf_wheel_rf3_0.geometry} material={materials['wheel_rf.3']} />
            <mesh geometry={nodes.wheel_rf_wheel_rf4_0.geometry} material={materials['wheel_rf.4']} />
            <mesh geometry={nodes.wheel_rf_wheel_rf5_0.geometry} material={materials['wheel_rf.5']} />
          </group>
        </group>
        <mesh geometry={nodes.Ground_Material001_0.geometry} material={materials['Material.001']} rotation={[-Math.PI / 2, 0, 0]} scale={[294.773, 421.552, 594.069]} />
      </group>
    </group>
  )
}

useGLTF.preload('/XL_Three.glb')
